### ISSUE TITLE
Error HTTP500 with the Demo quickstart

### ISSUE THREAD

**Issue by 87113** [sebo-b/warp#29]
Hi, 
I want to try WARP on my computer. I followed the doc here ; https://github.com/sebo-b/warp#demo-quickstart 

I did the git clone without any errors. 

When I executed the `docker compose` I got an error HTTP 500 on the url http://127.0.0.1:8080/ 

Here are the traces: 

```
(base) pascal@pascal-xps:~/Dev/warp$ docker compose -f demo_compose.yaml up
[+] Running 20/20
 ⠿ warp-demo-nginx Pulled                                                                                                                               10.8s
   ⠿ f03b40093957 Pull complete                                                                                                                          6.9s
   ⠿ eed12bbd6494 Pull complete                                                                                                                          7.5s
   ⠿ fa7eb8c8eee8 Pull complete                                                                                                                          7.6s
   ⠿ 7ff3b2b12318 Pull complete                                                                                                                          7.7s
   ⠿ 0f67c7de5f2c Pull complete                                                                                                                          7.8s
   ⠿ 831f51541d38 Pull complete                                                                                                                          7.9s
 ⠿ warp-demo-db Pulled                                                                                                                                  24.4s
   ⠿ 9d674c93414d Pull complete                                                                                                                          7.0s
   ⠿ de781e8e259a Pull complete                                                                                                                          7.6s
   ⠿ 5ea6efaf51f6 Pull complete                                                                                                                          7.8s
   ⠿ b078d5f4ac82 Pull complete                                                                                                                          8.4s
   ⠿ 97f84fb2a918 Pull complete                                                                                                                          8.7s
   ⠿ 5a6bf2f43fb8 Pull complete                                                                                                                          8.8s
   ⠿ f1a40e88fea4 Pull complete                                                                                                                          9.0s
   ⠿ 4be673794a1a Pull complete                                                                                                                         21.2s
   ⠿ 9d72f84fb861 Pull complete                                                                                                                         21.3s
   ⠿ 5d52569da92e Pull complete                                                                                                                         21.4s
   ⠿ 5d48fbe991ff Pull complete                                                                                                                         21.4s
   ⠿ 4ae692d11ad3 Pull complete                                                                                                                         21.5s
[+] Building 119.9s (27/28)                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                     0.1s
 => => transferring dockerfile: 1.77kB                                                                                                                   0.1s
 => [internal] load .dockerignore                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                          0.1s
 => [internal] load metadata for docker.io/library/python:3-slim                                                                                       119.6s
 => [compile-image  1/19] FROM docker.io/library/python:3-slim@sha256:eaee5f73efa9ae962d2077756292bc4878c04fcbc13dc168bb00cc365f35647e                   3.2s
 => => resolve docker.io/library/python:3-slim@sha256:eaee5f73efa9ae962d2077756292bc4878c04fcbc13dc168bb00cc365f35647e                                   0.1s
 => => sha256:05c2151a829c7c573d1d540463c8928df99235dca88fba7ae468657f3a0dda73 1.08MB / 1.08MB                                                           1.2s
 => => sha256:d31163dd7cf1fe77e2bb90104ec4d35cff4b4763dc39a431e376a4a93985a14f 11.94MB / 11.94MB                                                         2.0s
 => => sha256:e2dbff2a8d756ecb457f520679428777b7b0df55c2302fda65efb6281460f8e6 244B / 244B                                                               0.2s
 => => sha256:eaee5f73efa9ae962d2077756292bc4878c04fcbc13dc168bb00cc365f35647e 1.65kB / 1.65kB                                                           0.0s
 => => sha256:7b866f12347fbfccbb73284d9c04bbd67b5f9cca8b46786e9fa2bd07af53f09a 1.37kB / 1.37kB                                                           0.0s
 => => sha256:e77f21686f0b6267e49062c42fdf37aa9b87006eb07f402ba0acea8bed38ac06 6.83kB / 6.83kB                                                           0.0s
 => => sha256:10fe820b307733181983e560080d8ef1d79cf8f2fd8105fa3e020dbe4fe2d606 3.37MB / 3.37MB                                                           1.6s
 => => extracting sha256:05c2151a829c7c573d1d540463c8928df99235dca88fba7ae468657f3a0dda73                                                                0.1s
 => => extracting sha256:d31163dd7cf1fe77e2bb90104ec4d35cff4b4763dc39a431e376a4a93985a14f                                                                0.3s
 => => extracting sha256:e2dbff2a8d756ecb457f520679428777b7b0df55c2302fda65efb6281460f8e6                                                                0.0s
 => => extracting sha256:10fe820b307733181983e560080d8ef1d79cf8f2fd8105fa3e020dbe4fe2d606                                                                0.2s
 => [internal] load build context                                                                                                                        0.6s
 => => transferring context: 4.20MB                                                                                                                      0.6s
 => [compile-image  2/19] WORKDIR /opt/warp                                                                                                              0.6s
 => [compile-image  3/19] RUN apt-get update                                                                                                             3.3s
 => [compile-image  4/19] RUN mkdir debs &&     apt-get install -y -d --no-install-recommends libpq5 mime-support &&     cp /var/cache/apt/archives/*de  2.5s
 => [compile-image  5/19] RUN     apt-get install -y wget &&     NODE_ARCH=$(uname -m | sed 's/^x86_64\|amd64$/x64/;s/^i.*86$/x86/;s/^aarch64$/arm64/')  6.8s 
 => [compile-image  6/19] RUN apt-get install -y build-essential libpq-dev libpcre3 libpcre3-dev                                                        45.8s 
 => [compile-image  7/19] RUN pip install --upgrade setuptools && pip install wheel uwsgi                                                                9.7s 
 => [compile-image  8/19] RUN pip wheel -w wheel/ uwsgi                                                                                                  0.9s 
 => [compile-image  9/19] WORKDIR /opt/warp/js/                                                                                                          0.1s 
 => [compile-image 10/19] COPY js/package.json js/package-lock.json ./                                                                                   0.2s 
 => [compile-image 11/19] RUN npm ci                                                                                                                    11.0s 
 => [compile-image 12/19] COPY js/ ./                                                                                                                    0.1s 
 => [compile-image 13/19] RUN npm run build                                                                                                              7.0s 
 => [compile-image 14/19] WORKDIR /opt/warp                                                                                                              0.2s 
 => [compile-image 15/19] COPY requirements.txt ./                                                                                                       0.1s 
 => [compile-image 16/19] RUN pip wheel -w wheel -r requirements.txt                                                                                    11.8s
 => [compile-image 17/19] COPY warp ./warp                                                                                                               0.2s
 => [compile-image 18/19] COPY setup.py MANIFEST.in ./                                                                                                   0.1s
 => [compile-image 19/19] RUN python setup.py bdist_wheel -d wheel                                                                                       0.8s
 => [stage-1 3/6] RUN     --mount=type=bind,from=compile-image,source=/opt/warp/debs,target=./debs     dpkg -i debs/*.deb                                3.8s
 => [stage-1 4/6] RUN     --mount=type=bind,from=compile-image,source=/opt/warp/wheel,target=./wheel     pip install --no-index wheel/*.whl              3.6s
 => [stage-1 5/6] COPY --from=compile-image /opt/warp/warp/static ./static                                                                               0.2s
 => [stage-1 6/6] COPY res/warp_uwsgi.ini .                                                                                                              0.1s
 => exporting to image                                                                                                                                   0.5s
 => => exporting layers                                                                                                                                  0.5s
 => => writing image sha256:56609d4a45ff9aeb691d6fc411a80162534a4d29acdd33b6592bff08af535abd                                                             0.0s
 => => naming to docker.io/library/warp-warp-demo-wsgi                                                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 4/4
 ⠿ Network warp_default              Created                                                                                                             0.2s
 ⠿ Container warp-warp-demo-db-1     Created                                                                                                             0.6s
 ⠿ Container warp-warp-demo-wsgi-1   Created                                                                                                             0.3s
 ⠿ Container warp-warp-demo-nginx-1  Created                                                                                                             0.4s
Attaching to warp-warp-demo-db-1, warp-warp-demo-nginx-1, warp-warp-demo-wsgi-1
warp-warp-demo-db-1     | The files belonging to this database system will be owned by user "postgres".
warp-warp-demo-db-1     | This user must also own the server process.
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | The database cluster will be initialized with locale "en_US.utf8".
warp-warp-demo-db-1     | The default database encoding has accordingly been set to "UTF8".
warp-warp-demo-db-1     | The default text search configuration will be set to "english".
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | Data page checksums are disabled.
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
warp-warp-demo-db-1     | creating subdirectories ... ok
warp-warp-demo-db-1     | selecting dynamic shared memory implementation ... posix
warp-warp-demo-db-1     | selecting default max_connections ... 100
warp-warp-demo-db-1     | selecting default shared_buffers ... 128MB
warp-warp-demo-db-1     | selecting default time zone ... Etc/UTC
warp-warp-demo-db-1     | creating configuration files ... ok
warp-warp-demo-db-1     | running bootstrap script ... ok
warp-warp-demo-wsgi-1   | [uWSGI] getting INI configuration from warp_uwsgi.ini
warp-warp-demo-db-1     | performing post-bootstrap initialization ... ok
warp-warp-demo-wsgi-1   | *** Starting uWSGI 2.0.21 (64bit) on [Mon Jun  5 14:55:05 2023] ***
warp-warp-demo-wsgi-1   | compiled with version: 10.2.1 20210110 on 05 June 2023 14:54:15
warp-warp-demo-wsgi-1   | os: Linux-5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022
warp-warp-demo-wsgi-1   | nodename: 37a385307f73
warp-warp-demo-wsgi-1   | machine: x86_64
warp-warp-demo-wsgi-1   | clock source: unix
warp-warp-demo-wsgi-1   | pcre jit disabled
warp-warp-demo-wsgi-1   | detected number of CPU cores: 6
warp-warp-demo-wsgi-1   | current working directory: /opt/warp
warp-warp-demo-wsgi-1   | detected binary path: /usr/local/bin/uwsgi
warp-warp-demo-wsgi-1   | *** dumping internal routing table ***
warp-warp-demo-wsgi-1   | [rule: 0] subject: path_info regexp: ^/static/ action: goto:static
warp-warp-demo-wsgi-1   | [rule: 1] action: last:
warp-warp-demo-wsgi-1   | [rule: 2] label: static
warp-warp-demo-wsgi-1   | [rule: 3] subject: path_info regexp: ^/static/(.*) action: rewrite:$1
warp-warp-demo-wsgi-1   | [rule: 4] subject: /opt/warp/static/${PATH_INFO} func: isfile action: static:/opt/warp/static/${PATH_INFO}
warp-warp-demo-wsgi-1   | [rule: 5] action: addheader:Cache-Control: no-cache
warp-warp-demo-wsgi-1   | [rule: 6] action: return:404
warp-warp-demo-wsgi-1   | *** end of the internal routing table ***
warp-warp-demo-wsgi-1   | uWSGI running as root, you can use --uid/--gid/--chroot options
warp-warp-demo-wsgi-1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
warp-warp-demo-wsgi-1   | your memory page size is 4096 bytes
warp-warp-demo-wsgi-1   | detected max file descriptor number: 1048576
warp-warp-demo-wsgi-1   | building mime-types dictionary from file /etc/mime.types...1476 entry found
warp-warp-demo-wsgi-1   | lock engine: pthread robust mutexes
warp-warp-demo-wsgi-1   | thunder lock: disabled (you can enable it with --thunder-lock)
warp-warp-demo-wsgi-1   | uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 6
warp-warp-demo-wsgi-1   | uWSGI running as root, you can use --uid/--gid/--chroot options
warp-warp-demo-wsgi-1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
warp-warp-demo-wsgi-1   | Python version: 3.11.3 (main, May 23 2023, 13:34:03) [GCC 10.2.1 20210110]
warp-warp-demo-wsgi-1   | Python main interpreter initialized at 0x7f12ea63e558
warp-warp-demo-wsgi-1   | uWSGI running as root, you can use --uid/--gid/--chroot options
warp-warp-demo-wsgi-1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
warp-warp-demo-wsgi-1   | python threads support enabled
warp-warp-demo-wsgi-1   | your server socket listen backlog is limited to 100 connections
warp-warp-demo-wsgi-1   | your mercy for graceful operations on workers is 60 seconds
warp-warp-demo-wsgi-1   | mapped 703440 bytes (686 KB) for 8 cores
warp-warp-demo-wsgi-1   | *** Operational MODE: preforking+threaded ***
warp-warp-demo-wsgi-1   | Traceback (most recent call last):
warp-warp-demo-wsgi-1   |   File "/usr/local/lib/python3.11/site-packages/warp/__init__.py", line 9, in create_app
warp-warp-demo-wsgi-1   |     initConfig(app)
warp-warp-demo-wsgi-1   |   File "/usr/local/lib/python3.11/site-packages/warp/config.py", line 109, in initConfig
warp-warp-demo-wsgi-1   |     if app.env != 'production':
warp-warp-demo-wsgi-1   |        ^^^^^^^
warp-warp-demo-wsgi-1   | AttributeError: 'Flask' object has no attribute 'env'
warp-warp-demo-wsgi-1   | unable to load app 0 (mountpoint='') (callable not found or import error)
warp-warp-demo-wsgi-1   | *** no app loaded. going in full dynamic mode ***
warp-warp-demo-wsgi-1   | uWSGI running as root, you can use --uid/--gid/--chroot options
warp-warp-demo-wsgi-1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
warp-warp-demo-wsgi-1   | *** uWSGI is running in multiple interpreter mode ***
warp-warp-demo-wsgi-1   | spawned uWSGI master process (pid: 1)
warp-warp-demo-wsgi-1   | spawned uWSGI worker 1 (pid: 7, cores: 2)
warp-warp-demo-wsgi-1   | spawned 2 offload threads for uWSGI worker 1
warp-warp-demo-wsgi-1   | spawned uWSGI worker 2 (pid: 10, cores: 2)
warp-warp-demo-wsgi-1   | spawned 2 offload threads for uWSGI worker 2
warp-warp-demo-wsgi-1   | spawned uWSGI worker 3 (pid: 14, cores: 2)
warp-warp-demo-wsgi-1   | spawned 2 offload threads for uWSGI worker 3
warp-warp-demo-wsgi-1   | spawned uWSGI worker 4 (pid: 18, cores: 2)
warp-warp-demo-wsgi-1   | spawned 2 offload threads for uWSGI worker 4
warp-warp-demo-db-1     | syncing data to disk ... ok
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | Success. You can now start the database server using:
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | initdb: warning: enabling "trust" authentication for local connections
warp-warp-demo-db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
warp-warp-demo-db-1     | waiting for server to start....2023-06-05 14:55:05.713 UTC [49] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
warp-warp-demo-db-1     | 2023-06-05 14:55:05.722 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
warp-warp-demo-db-1     | 2023-06-05 14:55:05.743 UTC [52] LOG:  database system was shut down at 2023-06-05 14:55:05 UTC
warp-warp-demo-db-1     | 2023-06-05 14:55:05.753 UTC [49] LOG:  database system is ready to accept connections
warp-warp-demo-db-1     |  done
warp-warp-demo-db-1     | server started
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | waiting for server to shut down...2023-06-05 14:55:05.829 UTC [49] LOG:  received fast shutdown request
warp-warp-demo-db-1     | .2023-06-05 14:55:05.835 UTC [49] LOG:  aborting any active transactions
warp-warp-demo-db-1     | 2023-06-05 14:55:05.836 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
warp-warp-demo-db-1     | 2023-06-05 14:55:05.837 UTC [50] LOG:  shutting down
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
warp-warp-demo-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
warp-warp-demo-db-1     | 2023-06-05 14:55:05.842 UTC [50] LOG:  checkpoint starting: shutdown immediate
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
warp-warp-demo-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: using the "epoll" event method
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: nginx/1.25.0
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: OS: Linux 5.15.49-linuxkit
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker processes
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 21
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 22
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 23
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 24
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 25
warp-warp-demo-nginx-1  | 2023/06/05 14:55:05 [notice] 1#1: start worker process 26
warp-warp-demo-db-1     | 2023-06-05 14:55:05.900 UTC [50] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.006 s, total=0.064 s; sync files=2, longest=0.003 s, average=0.003 s; distance=0 kB, estimate=0 kB
warp-warp-demo-db-1     | 2023-06-05 14:55:05.916 UTC [49] LOG:  database system is shut down
warp-warp-demo-db-1     |  done
warp-warp-demo-db-1     | server stopped
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | PostgreSQL init process complete; ready for start up.
warp-warp-demo-db-1     | 
warp-warp-demo-db-1     | 2023-06-05 14:55:05.976 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
warp-warp-demo-db-1     | 2023-06-05 14:55:05.977 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
warp-warp-demo-db-1     | 2023-06-05 14:55:05.977 UTC [1] LOG:  listening on IPv6 address "::", port 5432
warp-warp-demo-db-1     | 2023-06-05 14:55:05.988 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
warp-warp-demo-db-1     | 2023-06-05 14:55:06.002 UTC [63] LOG:  database system was shut down at 2023-06-05 14:55:05 UTC
warp-warp-demo-db-1     | 2023-06-05 14:55:06.012 UTC [1] LOG:  database system is ready to accept connections
warp-warp-demo-wsgi-1   | --- no python application found, check your startup logs for errors ---
warp-warp-demo-wsgi-1   | [pid: 18|app: -1|req: -1/1] 172.23.0.1 () {50 vars in 887 bytes} [Mon Jun  5 14:57:44 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
warp-warp-demo-nginx-1  | 172.23.0.1 - - [05/Jun/2023:14:57:44 +0000] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" "-"
warp-warp-demo-wsgi-1   | --- no python application found, check your startup logs for errors ---
warp-warp-demo-nginx-1  | 172.23.0.1 - - [05/Jun/2023:14:57:44 +0000] "GET /favicon.ico HTTP/1.1" 500 32 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" "-"
warp-warp-demo-wsgi-1   | [pid: 14|app: -1|req: -1/2] 172.23.0.1 () {48 vars in 824 bytes} [Mon Jun  5 14:57:44 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
warp-warp-demo-db-1     | 2023-06-05 15:00:06.109 UTC [61] LOG:  checkpoint starting: time
warp-warp-demo-db-1     | 2023-06-05 15:00:10.202 UTC [61] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.038 s, sync=0.020 s, total=4.093 s; sync files=11, longest=0.010 s, average=0.002 s; distance=252 kB, estimate=252 kB
warp-warp-demo-nginx-1  | 172.23.0.1 - - [05/Jun/2023:15:39:19 +0000] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" "-"
warp-warp-demo-wsgi-1   | --- no python application found, check your startup logs for errors ---
warp-warp-demo-wsgi-1   | [pid: 18|app: -1|req: -1/3] 172.23.0.1 () {54 vars in 940 bytes} [Mon Jun  5 15:39:19 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
warp-warp-demo-wsgi-1   | --- no python application found, check your startup logs for errors ---
warp-warp-demo-wsgi-1   | [pid: 14|app: -1|req: -1/4] 172.23.0.1 () {52 vars in 877 bytes} [Mon Jun  5 15:39:20 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
warp-warp-demo-nginx-1  | 172.23.0.1 - - [05/Jun/2023:15:39:20 +0000] "GET /favicon.ico HTTP/1.1" 500 32 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" "-"
```

**Comment by sebo-b** [comment]
This is because of changes in Flask 2.3. I need to do a general check to see if there are other significant changes that may break warp. In the time being, it should help (I haven't tested though) if you edit `requirements.txt` and add `2.2.5` version to `flask`, something like this:

```
flask == 2.2.5
```

**Comment by 87113** [comment]
Thank you for your quick answer. 

Unfortunately I tried with `flask == 2.2.5` but I got the same message.

**Comment by sebo-b** [comment]
@87113 try clean build, with the above fix it works for me
