### ISSUE TITLE
Application not starting since python 3.13

### ISSUE THREAD

**Issue by alexuwork** [sebo-b/warp#56]
Hello,
the application worked fine the last days, since yesterday its not working anymore, i also installed the application complettly new but the same errors,
i use now python3.12 , flask 2.2.* and werkzeug 2.2.*
but i get some errors after compiling.
can someone please help me ?

Thank you

warp-demo-wsgi-1   | Traceback (most recent call last):
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
warp-demo-wsgi-1   |     response = self.full_dispatch_request()
warp-demo-wsgi-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
warp-demo-wsgi-1   |     rv = self.handle_user_exception(e)
warp-demo-wsgi-1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
warp-demo-wsgi-1   |     rv = self.dispatch_request()
warp-demo-wsgi-1   |          ^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
warp-demo-wsgi-1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
warp-demo-wsgi-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/warp/auth.py", line 48, in login
warp-demo-wsgi-1   |     return flask.render_template('login.html')
warp-demo-wsgi-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
warp-demo-wsgi-1   |     return _render(app, template, context)
warp-demo-wsgi-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
warp-demo-wsgi-1   |     rv = template.render(context)
warp-demo-wsgi-1   |          ^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
warp-demo-wsgi-1   |     self.environment.handle_exception()
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
warp-demo-wsgi-1   |     raise rewrite_traceback_stack(source=source)
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/warp/templates/login.html", line 1, in top-level template code
warp-demo-wsgi-1   |     {% extends 'base.html' %}
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/warp/templates/base.html", line 35, in top-level template code
warp-demo-wsgi-1   |     {% include 'headers/base.html' %}
warp-demo-wsgi-1   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 62, in get_source
warp-demo-wsgi-1   |     return self._get_source_fast(environment, template)
warp-demo-wsgi-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-demo-wsgi-1   |   File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 98, in _get_source_fast
warp-demo-wsgi-1   |     raise TemplateNotFound(template)
warp-demo-wsgi-1   | jinja2.exceptions.TemplateNotFound: headers/base.html

**Comment by sebo-b** [comment]
seems to be fixed now
